apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimalapi-deployment
  labels:
    app: minimalapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minimalapi
  template:
    metadata:
      labels:
        app: minimalapi
    spec:
      containers:
        - name: minimalapi-dotnet6
          image: alissonrocio/minimalapi-dotnet6:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: minimalapi-service
spec:
  type: NodePort
  ports:
    - port: 8088
      targetPort: 80
      protocol: TCP
  selector:
    app: minimalapi
